CREATE TABLE `historial_calculos` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`loteId` int,
	`codigoLote` varchar(50),
	`numAnimales` int NOT NULL,
	`usaCostesEstimados` int NOT NULL DEFAULT 1,
	`e57_precioKg` decimal(8,4),
	`e57_ingresosPorAnimal` decimal(10,2),
	`e57_costeTotalPorAnimal` decimal(10,2),
	`e57_margenPorAnimal` decimal(10,2),
	`e57_margenTotal` decimal(12,2),
	`e57_margenPorPlazaDia` decimal(8,4),
	`e57_rentabilidadPct` decimal(8,2),
	`e57_mortalidadPct` decimal(5,2),
	`e57_viable` int NOT NULL DEFAULT 1,
	`e2021_precioKg` decimal(8,4),
	`e2021_ingresosPorAnimal` decimal(10,2),
	`e2021_costeTotalPorAnimal` decimal(10,2),
	`e2021_margenPorAnimal` decimal(10,2),
	`e2021_margenTotal` decimal(12,2),
	`e2021_margenPorPlazaDia` decimal(8,4),
	`e2021_rentabilidadPct` decimal(8,2),
	`e2021_mortalidadPct` decimal(5,2),
	`e2021_viable` int NOT NULL DEFAULT 1,
	`eCebo_precioKg` decimal(8,4),
	`eCebo_ingresosPorAnimal` decimal(10,2),
	`eCebo_costeTotalPorAnimal` decimal(10,2),
	`eCebo_margenPorAnimal` decimal(10,2),
	`eCebo_margenTotal` decimal(12,2),
	`eCebo_margenPorPlazaDia` decimal(8,4),
	`eCebo_rentabilidadPct` decimal(8,2),
	`eCebo_mortalidadPct` decimal(5,2),
	`eCebo_viable` int NOT NULL DEFAULT 1,
	`escenarioRecomendado` varchar(20),
	`confianzaRecomendacion` decimal(3,2),
	`precioMercadoCebado` decimal(8,4),
	`precioMercadoLechon20` decimal(8,2),
	`precioMercadoLechon7` decimal(8,4),
	`precioMercadoPienso` decimal(8,2),
	`notas` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `historial_calculos_id` PRIMARY KEY(`id`)
);
